services:
  - type: web
    name: ydy-downloader
    env: python
    buildCommand: |
      apt-get -y update
      apt-get -y install ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app